version: "3"
services:  
  api:
    container_name: plv_api
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./api:/var/www/api
      - ./tests:/var/www/tests
      

  app:
    container_name: plv_app
    build:
      context: ./ui
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"