version: "3"
services:  
  api:
    container_name: plv_api
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
      

  app:
    container_name: plv_app
    build:
      context: ./app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"